name: Manual - Implement Org Labels
# Note that the actual org labels are not accessible through the API,
# so we use global-api-devops as the source of truth. Make sure it is updated as well.

on: workflow_dispatch

jobs:
  implement-org-labels:
    runs-on: ubuntu-latest # public repo, keep this here
    timeout-minutes: 3
    steps:
      - name: Call API for Implementing Org Labels
        uses: dkershner6/post-api-call-action@v1
        with:
          url: 'https://api.devops.eformedpartners.com/github/repos/${{ github.repository }}/org_labels'
          headers: '{"Authorization": "Bearer ${{ secrets.DEVOPS_API_KEY }}"}'
