name: PR to Main

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    

jobs:        
  build-check:
    runs-on: ubuntu-latest # public repo, keep this here
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
          scope: "@obfns"
      - name: Build Docusaurus
        run: |
          npm ci
          npm run lint
          npm run build
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.READ_GH_PACKAGES_TOKEN }}